# Generated by Django 5.2.3 on 2025-08-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('time_zone', models.CharField(default='America/New_York', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Ads Account',
                'verbose_name_plural': 'Google Ads Accounts',
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BUDGET', 'Budget Alert'), ('PERFORMANCE', 'Performance Alert'), ('QUALITY_SCORE', 'Quality Score Alert'), ('POLICY_VIOLATION', 'Policy Violation'), ('SYSTEM', 'System Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='google_ads_app.googleadsaccount')),
            ],
            options={
                'verbose_name': 'Google Ads Alert',
                'verbose_name_plural': 'Google Ads Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=20)),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_status', models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ENABLED', max_length=20)),
                ('campaign_type', models.CharField(choices=[('SEARCH', 'Search'), ('DISPLAY', 'Display'), ('VIDEO', 'Video'), ('SHOPPING', 'Shopping'), ('PERFORMANCE_MAX', 'Performance Max')], default='SEARCH', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_type', models.CharField(default='DAILY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='google_ads_app.googleadsaccount')),
            ],
            options={
                'verbose_name': 'Google Ads Campaign',
                'verbose_name_plural': 'Google Ads Campaigns',
                'unique_together': {('account', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsAdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.CharField(max_length=20)),
                ('ad_group_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ENABLED', max_length=20)),
                ('type', models.CharField(default='STANDARD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='google_ads_app.googleadscampaign')),
            ],
            options={
                'verbose_name': 'Google Ads Ad Group',
                'verbose_name_plural': 'Google Ads Ad Groups',
                'unique_together': {('campaign', 'ad_group_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.CharField(max_length=20)),
                ('keyword_text', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('PHRASE', 'Phrase'), ('BROAD', 'Broad'), ('BROAD_MATCH_MODIFIER', 'Broad Match Modifier')], default='BROAD', max_length=25)),
                ('status', models.CharField(default='ENABLED', max_length=20)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='google_ads_app.googleadsadgroup')),
            ],
            options={
                'verbose_name': 'Google Ads Keyword',
                'verbose_name_plural': 'Google Ads Keywords',
                'unique_together': {('ad_group', 'keyword_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('ACCOUNT_PERFORMANCE', 'Account Performance'), ('CAMPAIGN_PERFORMANCE', 'Campaign Performance'), ('AD_GROUP_PERFORMANCE', 'Ad Group Performance'), ('KEYWORD_PERFORMANCE', 'Keyword Performance'), ('GEO_PERFORMANCE', 'Geographic Performance'), ('DEVICE_PERFORMANCE', 'Device Performance')], max_length=25)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20)),
                ('schedule', models.CharField(default='DAILY', max_length=50)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Ads Report',
                'verbose_name_plural': 'Google Ads Reports',
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost_micros', models.BigIntegerField(default=0)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('roas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='google_ads_app.googleadsaccount')),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='google_ads_app.googleadsadgroup')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='google_ads_app.googleadscampaign')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='google_ads_app.googleadskeyword')),
            ],
            options={
                'verbose_name': 'Google Ads Performance',
                'verbose_name_plural': 'Google Ads Performance Data',
                'indexes': [models.Index(fields=['date'], name='google_ads__date_d6f6e4_idx'), models.Index(fields=['account', 'date'], name='google_ads__account_dd7e60_idx'), models.Index(fields=['campaign', 'date'], name='google_ads__campaig_f48797_idx')],
                'unique_together': {('account', 'date', 'campaign', 'ad_group', 'keyword')},
            },
        ),
    ]
