# Generated by Django 5.2.3 on 2025-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadsaccount',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='True if this is a manager account (MCC) that can manage other sub-accounts'),
        ),
        migrations.AddField(
            model_name='googleadsaccount',
            name='is_test_account',
            field=models.BooleanField(default=False, help_text='True if this is a test/sandbox account'),
        ),
    ]
