# Generated by Django 5.2.3 on 2025-08-24 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads_new', '0002_googleadsaccount_is_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('document_type', models.CharField(default='general', max_length=50)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Document',
                'verbose_name_plural': 'Knowledge Base Documents',
                'db_table': 'kb_documents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company_id'], name='kb_document_company_910948_idx'), models.Index(fields=['document_type'], name='kb_document_documen_ee31c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='google_ads_new.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx'), models.Index(fields=['role', 'created_at'], name='chat_messag_role_b6a95d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('google_ads', 'Google Ads API'), ('database', 'Database Query'), ('knowledge_base', 'Knowledge Base Search'), ('analytics', 'Analytics Generation'), ('campaign_management', 'Campaign Management')], max_length=30)),
                ('tool_name', models.CharField(max_length=100)),
                ('input_parameters', models.JSONField(default=dict)),
                ('output_result', models.JSONField(default=dict)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tool_executions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='google_ads_new.chatsession')),
            ],
            options={
                'verbose_name': 'AI Tool Execution',
                'verbose_name_plural': 'AI Tool Executions',
                'db_table': 'ai_tool_executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_tool_exe_user_id_bc0851_idx'), models.Index(fields=['tool_type', 'success'], name='ai_tool_exe_tool_ty_6dd382_idx'), models.Index(fields=['session', 'created_at'], name='ai_tool_exe_session_326305_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('detected_intent', models.CharField(max_length=100)),
                ('intent_confidence', models.FloatField(blank=True, null=True)),
                ('tool_calls', models.JSONField(default=dict)),
                ('response_blocks', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Intent',
                'verbose_name_plural': 'User Intents',
                'db_table': 'user_intents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_intent_user_id_d9b843_idx'), models.Index(fields=['detected_intent'], name='user_intent_detecte_f28ac7_idx')],
            },
        ),
    ]
