# Generated by Django 5.2.5 on 2025-08-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads_new", "0002_add_memory_system"),
        (
            "google_ads_new",
            "0003_chatsession_kbdocument_chatmessage_aitoolexecution_and_more",
        ),
    ]

    operations = []
