# Generated by Django 5.2.5 on 2025-08-29 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads_new", "0004_merge_20250829_1034"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryPatternMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_text",
                    models.TextField(help_text="The actual query pattern text"),
                ),
                (
                    "pattern_type",
                    models.CharField(help_text="Type of query pattern", max_length=100),
                ),
                (
                    "entities_extracted",
                    models.JSONField(
                        default=list, help_text="Entities found in this pattern"
                    ),
                ),
                (
                    "intent_detected",
                    models.CharField(
                        help_text="Intent detected for this pattern", max_length=100
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0, help_text="How successful this pattern was"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=1, help_text="Number of times this pattern was used"
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Query Pattern Memory",
                "verbose_name_plural": "Query Pattern Memories",
                "db_table": "query_pattern_memory",
            },
        ),
        migrations.RemoveIndex(
            model_name="adaptiveresponsepattern",
            name="adaptive_re_user_id_4d8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmemory",
            new_name="conversatio_user_id_037e88_idx",
            old_name="conversation_user_id_2b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmemory",
            new_name="conversatio_session_b02174_idx",
            old_name="conversation_session_8f9c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmemory",
            new_name="conversatio_last_ac_3f7db3_idx",
            old_name="conversation_last_ac_9d8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="crosssessionmemory",
            new_name="cross_sessi_user_id_c76fac_idx",
            old_name="cross_sessio_user_id_1a8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="crosssessionmemory",
            new_name="cross_sessi_importa_05ce95_idx",
            old_name="cross_sessio_importa_2b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="crosssessionmemory",
            new_name="cross_sessi_expires_c7e040_idx",
            old_name="cross_sessio_expires_3c8c8c_idx",
        ),
        migrations.AddField(
            model_name="conversationmemory",
            name="entity_mentions",
            field=models.JSONField(
                default=list, help_text="Entities mentioned in conversation"
            ),
        ),
        migrations.AddField(
            model_name="conversationmemory",
            name="query_patterns",
            field=models.JSONField(
                default=list, help_text="Query patterns and structures"
            ),
        ),
        migrations.AddField(
            model_name="usermemory",
            name="google_ads_expertise",
            field=models.JSONField(
                default=dict, help_text="Google Ads specific expertise areas"
            ),
        ),
        migrations.AddField(
            model_name="usermemory",
            name="query_patterns",
            field=models.JSONField(
                default=list, help_text="Common query patterns and preferences"
            ),
        ),
        migrations.AddField(
            model_name="querypatternmemory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="querypatternmemory",
            index=models.Index(
                fields=["user", "pattern_type"], name="query_patte_user_id_8ff965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querypatternmemory",
            index=models.Index(
                fields=["success_rate"], name="query_patte_success_2cc84a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querypatternmemory",
            index=models.Index(
                fields=["last_used"], name="query_patte_last_us_e0ae3f_idx"
            ),
        ),
    ]
