# Generated by Django 5.2.5 on 2025-08-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google_ads_new", "0005_querypatternmemory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmemory",
            name="entity_mentions",
        ),
        migrations.RemoveField(
            model_name="conversationmemory",
            name="query_patterns",
        ),
        migrations.RemoveField(
            model_name="usermemory",
            name="google_ads_expertise",
        ),
        migrations.RemoveField(
            model_name="usermemory",
            name="query_patterns",
        ),
        migrations.DeleteModel(
            name="QueryPatternMemory",
        ),
    ]
