# Generated by Django 5.2.5 on 2025-09-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_expert", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OAuthConnection",
        ),
    ]
