# Generated by Django 5.2.5 on 2025-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_expert", "0002_remove_oauth_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="customer_id",
            field=models.CharField(
                blank=True,
                help_text="Google Ads customer ID for this conversation",
                max_length=100,
                null=True,
            ),
        ),
    ]
