# Generated by Django 5.2.5 on 2025-08-19 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Google OAuth access token')),
                ('refresh_token', models.TextField(help_text='Google OAuth refresh token')),
                ('token_expiry', models.DateTimeField(help_text='When the access token expires')),
                ('google_user_id', models.CharField(help_text='Google user ID', max_length=100, unique=True)),
                ('google_email', models.EmailField(help_text='Google account email', max_length=254)),
                ('google_name', models.CharField(help_text='Google account display name', max_length=255)),
                ('google_ads_customer_id', models.CharField(blank=True, help_text='Google Ads customer ID', max_length=20, null=True)),
                ('google_ads_account_name', models.CharField(blank=True, help_text='Google Ads account name', max_length=255, null=True)),
                ('scopes', models.TextField(help_text='Comma-separated list of granted OAuth scopes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this OAuth connection is active')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this OAuth connection was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error encountered with this OAuth connection', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Google Auth',
                'verbose_name_plural': 'User Google Auths',
                'ordering': ['-last_used'],
            },
        ),
    ]
