# Generated by Django 5.2.3 on 2025-08-20 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usergoogleauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoogleauth',
            name='google_user_id',
            field=models.CharField(help_text='Google user ID', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='usergoogleauth',
            unique_together={('user', 'google_user_id')},
        ),
    ]
