# Generated by Django 5.2.3 on 2025-08-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usergoogleauth_user'),
    ]

    operations = [
    ]
