# Generated by Django 5.2.5 on 2025-09-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_google_user_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoogleauth",
            name="accessible_customers",
            field=models.JSONField(
                blank=True,
                help_text="List of accessible Google Ads customer IDs",
                null=True,
            ),
        ),
    ]
