# Generated by Django 5.2.5 on 2025-09-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_accessible_customers_field"),
    ]

    operations = []
