# Generated by Django 5.2.5 on 2025-09-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20250926_1250"),
    ]

    operations = []
