// 🎯 Complete Intent Actions Array
// Copy this array into your frontend application

const INTENT_ACTIONS = [
  // === BASIC GOOGLE ADS OPERATIONS ===
  "GET_OVERVIEW",
  "GET_CAMPAIGNS", 
  "CREATE_CAMPAIGN",
  "GET_ADS",
  "CREATE_AD",
  "PAUSE_CAMPAIGN",
  "RESUME_CAMPAIGN",
  "GET_PERFORMANCE",
  "GET_KEYWORDS",
  "GET_BUDGETS",

  // === ANALYSIS ACTIONS ===
  "CAMPAIGN_SUMMARY_COMPARISON",
  "PERFORMANCE_SUMMARY",
  "TREND_ANALYSIS",
  "LISTING_ANALYSIS",
  "PIE_CHART_DISPLAY",
  "DUPLICATE_KEYWORDS_ANALYSIS",
  "DIG_DEEPER_ANALYSIS",
  "COMPARE_PERFORMANCE",

  // === AUDIENCE & DEMOGRAPHICS ===
  "ANALYZE_AUDIENCE",
  "ANALYZE_AUDIENCE_INSIGHTS",
  "ANALYZE_DEMOGRAPHICS",

  // === CREATIVE ACTIONS ===
  "GENERATE_AD_COPIES",
  "GENERATE_CREATIVES",
  "POSTER_GENERATOR",
  "META_ADS_CREATIVES",
  "GENERATE_IMAGES",
  "TEST_CREATIVE_ELEMENTS",
  "CHECK_CREATIVE_FATIGUE",

  // === OPTIMIZATION ACTIONS ===
  "OPTIMIZE_CAMPAIGN",
  "OPTIMIZE_ADSET",
  "OPTIMIZE_AD",
  "OPTIMIZE_BUDGETS",
  "OPTIMIZE_TCPA",
  "OPTIMIZE_BUDGET_ALLOCATION",

  // === TECHNICAL ANALYSIS ===
  "CHECK_CAMPAIGN_CONSISTENCY",
  "CHECK_SITELINKS",
  "CHECK_LANDING_PAGE_URL",
  "CHECK_DUPLICATE_KEYWORDS",
  "CHECK_TECHNICAL_COMPLIANCE",

  // === PERFORMANCE ANALYSIS ===
  "ANALYZE_VIDEO_PERFORMANCE",
  "ANALYZE_PLACEMENTS",
  "ANALYZE_DEVICE_PERFORMANCE",
  "ANALYZE_DEVICE_PERFORMANCE_DETAILED",
  "ANALYZE_TIME_PERFORMANCE",
  "ANALYZE_LOCATION_PERFORMANCE",
  "ANALYZE_LANDING_PAGE_MOBILE",

  // === KEYWORD ANALYSIS ===
  "ANALYZE_KEYWORD_TRENDS",
  "ANALYZE_AUCTION_INSIGHTS",
  "ANALYZE_SEARCH_TERMS",
  "SUGGEST_NEGATIVE_KEYWORDS",

  // === COMPETITIVE ANALYSIS ===
  "ANALYZE_COMPETITORS",
  "ANALYZE_ADS_SHOWING_TIME",

  // === KNOWLEDGE BASE ===
  "SEARCH_KB",
  "ADD_KB_DOCUMENT",
  "SEARCH_DB",

  // === ANALYTICS ===
  "GET_ANALYTICS",

  // === FALLBACK ACTIONS ===
  "QUERY_WITHOUT_SOLUTION",
  "query_understanding_fallback"
];

// 🏷️ Actions by Category
const ACTIONS_BY_CATEGORY = {
  basic_operations: [
    "GET_OVERVIEW", "GET_CAMPAIGNS", "CREATE_CAMPAIGN", "GET_ADS", "CREATE_AD",
    "PAUSE_CAMPAIGN", "RESUME_CAMPAIGN", "GET_PERFORMANCE", "GET_KEYWORDS", "GET_BUDGETS"
  ],
  analysis: [
    "CAMPAIGN_SUMMARY_COMPARISON", "PERFORMANCE_SUMMARY", "TREND_ANALYSIS",
    "LISTING_ANALYSIS", "PIE_CHART_DISPLAY", "DUPLICATE_KEYWORDS_ANALYSIS",
    "DIG_DEEPER_ANALYSIS", "COMPARE_PERFORMANCE"
  ],
  audience: [
    "ANALYZE_AUDIENCE", "ANALYZE_AUDIENCE_INSIGHTS", "ANALYZE_DEMOGRAPHICS"
  ],
  creative: [
    "GENERATE_AD_COPIES", "GENERATE_CREATIVES", "POSTER_GENERATOR",
    "META_ADS_CREATIVES", "GENERATE_IMAGES", "TEST_CREATIVE_ELEMENTS",
    "CHECK_CREATIVE_FATIGUE"
  ],
  optimization: [
    "OPTIMIZE_CAMPAIGN", "OPTIMIZE_ADSET", "OPTIMIZE_AD", "OPTIMIZE_BUDGETS",
    "OPTIMIZE_TCPA", "OPTIMIZE_BUDGET_ALLOCATION"
  ],
  technical: [
    "CHECK_CAMPAIGN_CONSISTENCY", "CHECK_SITELINKS", "CHECK_LANDING_PAGE_URL",
    "CHECK_DUPLICATE_KEYWORDS", "CHECK_TECHNICAL_COMPLIANCE"
  ],
  performance: [
    "ANALYZE_VIDEO_PERFORMANCE", "ANALYZE_PLACEMENTS", "ANALYZE_DEVICE_PERFORMANCE",
    "ANALYZE_DEVICE_PERFORMANCE_DETAILED", "ANALYZE_TIME_PERFORMANCE",
    "ANALYZE_LOCATION_PERFORMANCE", "ANALYZE_LANDING_PAGE_MOBILE"
  ],
  keywords: [
    "ANALYZE_KEYWORD_TRENDS", "ANALYZE_AUCTION_INSIGHTS", "ANALYZE_SEARCH_TERMS",
    "SUGGEST_NEGATIVE_KEYWORDS"
  ],
  competitive: [
    "ANALYZE_COMPETITORS", "ANALYZE_ADS_SHOWING_TIME"
  ],
  knowledge_base: [
    "SEARCH_KB", "ADD_KB_DOCUMENT", "SEARCH_DB"
  ],
  analytics: [
    "GET_ANALYTICS"
  ],
  fallback: [
    "QUERY_WITHOUT_SOLUTION", "query_understanding_fallback"
  ]
};

// 🔐 Actions that require authentication
const AUTH_REQUIRED_ACTIONS = [
  "GET_OVERVIEW", "GET_CAMPAIGNS", "CREATE_CAMPAIGN", "GET_ADS", "CREATE_AD",
  "PAUSE_CAMPAIGN", "RESUME_CAMPAIGN", "GET_PERFORMANCE", "GET_KEYWORDS", "GET_BUDGETS",
  "CAMPAIGN_SUMMARY_COMPARISON", "PERFORMANCE_SUMMARY", "TREND_ANALYSIS",
  "LISTING_ANALYSIS", "PIE_CHART_DISPLAY", "DUPLICATE_KEYWORDS_ANALYSIS",
  "DIG_DEEPER_ANALYSIS", "COMPARE_PERFORMANCE", "ANALYZE_AUDIENCE",
  "ANALYZE_AUDIENCE_INSIGHTS", "ANALYZE_DEMOGRAPHICS", "TEST_CREATIVE_ELEMENTS",
  "CHECK_CREATIVE_FATIGUE", "OPTIMIZE_CAMPAIGN", "OPTIMIZE_ADSET", "OPTIMIZE_AD",
  "OPTIMIZE_BUDGETS", "OPTIMIZE_TCPA", "OPTIMIZE_BUDGET_ALLOCATION",
  "CHECK_CAMPAIGN_CONSISTENCY", "CHECK_SITELINKS", "CHECK_LANDING_PAGE_URL",
  "CHECK_DUPLICATE_KEYWORDS", "CHECK_TECHNICAL_COMPLIANCE", "ANALYZE_VIDEO_PERFORMANCE",
  "ANALYZE_PLACEMENTS", "ANALYZE_DEVICE_PERFORMANCE", "ANALYZE_DEVICE_PERFORMANCE_DETAILED",
  "ANALYZE_TIME_PERFORMANCE", "ANALYZE_LOCATION_PERFORMANCE", "ANALYZE_LANDING_PAGE_MOBILE",
  "ANALYZE_KEYWORD_TRENDS", "ANALYZE_AUCTION_INSIGHTS", "ANALYZE_SEARCH_TERMS",
  "SUGGEST_NEGATIVE_KEYWORDS", "ANALYZE_COMPETITORS", "ANALYZE_ADS_SHOWING_TIME",
  "ADD_KB_DOCUMENT", "SEARCH_DB", "GET_ANALYTICS"
];

// 🆓 Actions that don't require authentication
const NO_AUTH_ACTIONS = [
  "GENERATE_AD_COPIES", "GENERATE_CREATIVES", "POSTER_GENERATOR",
  "META_ADS_CREATIVES", "GENERATE_IMAGES", "SEARCH_KB",
  "QUERY_WITHOUT_SOLUTION", "query_understanding_fallback"
];

// 📊 Statistics
const ACTION_STATS = {
  total: INTENT_ACTIONS.length,
  by_category: Object.keys(ACTIONS_BY_CATEGORY).reduce((acc, category) => {
    acc[category] = ACTIONS_BY_CATEGORY[category].length;
    return acc;
  }, {}),
  auth_required: AUTH_REQUIRED_ACTIONS.length,
  no_auth: NO_AUTH_ACTIONS.length
};

// 🛠️ Utility Functions
const getActionsByCategory = (category) => ACTIONS_BY_CATEGORY[category] || [];
const isAuthRequired = (action) => AUTH_REQUIRED_ACTIONS.includes(action);
const getRandomAction = () => INTENT_ACTIONS[Math.floor(Math.random() * INTENT_ACTIONS.length)];

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    INTENT_ACTIONS,
    ACTIONS_BY_CATEGORY,
    AUTH_REQUIRED_ACTIONS,
    NO_AUTH_ACTIONS,
    ACTION_STATS,
    getActionsByCategory,
    isAuthRequired,
    getRandomAction
  };
}

console.log('🎯 Intent Actions Loaded:', ACTION_STATS);

